const config = require('config')
const Midi = require('../lib/midi/midi')

const torsoT1OSC = require('../extra/osc/torso-t1.json')

function matrixSources() {
  let result = 4 + 126 // num of matrixSlotSources from bacara.js
  for (let addr in torsoT1OSC) {
    if (torsoT1OSC[addr].matrix) {
      result++
    }
  }
  return result
}

function deviceToIndex(portName, channel) {
  if (config.devices) {
    let idx = 1
    const deviceKeys = Object.keys(config.devices).filter( deviceKey => deviceKey != 'bacara' )
    deviceKeys.unshift('bacara')

    for (let deviceKey of deviceKeys) {
      if (Array.isArray(config.devices[deviceKey].channels)) {
        for (let c in config.devices[deviceKey].channels) {
          if (Midi.normalisePortName(portName) == Midi.normalisePortName(deviceKey) && channel == config.devices[deviceKey].channels[c]) {
            /*            debug('deviceToIndex %y %y => %y',portName, channel, idx)*/
            return idx
          }
          idx++
        }
      }
    }
  }
  debug('deviceToIndex %y %y => NOT FOUND', portName, channel)
}

module.exports = {

  elements: {
    load: {
      name: 'Load',
      type: 'action',
      surface: {
        type: 'sysex',
        bytes: [0xF0, 0x7D, 0x00, 0x03, 0xF7],
        number: 0x03,
      },
    },
    generate: {
      name: 'Generate',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 1281,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    temperature: {
      name: 'Temperature',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 1153,
        lsbFirst: true,
        min: 100,
        max: 500,
      },
      min: 1.0,
      max: 5.0,
      default: 1.0,
      precision: 3,
      unit: '°',
    },
    steps: {
      name: 'Steps',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 16260,
        lsbFirst: true,
        min: 1,
        max: 128,
      },
      external: {
        type: 'cc',
        number: 4,
        min: 0,
        max: 127,
      },
      min: 1,
      max: 128,
      default: 16,
      integer: true,
      unit: 'steps',
    },
    previous_pattern: {
      name: 'Previous Pattern',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 1409,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    next_pattern: {
      name: 'Next Pattern',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 1537,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    transpose: {
      name: 'Transpose',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 1665,
        lsbFirst: true,
        min: 0,
        max: 127,
      },
      external: {
        type: 'cc',
        number: 3,
        min: 0,
        max: 127,
      },
      min: -64,
      max: 63,
      default: 0,
      unit: 'notes',
    },
    scales: {
      name: 'Scales Mode',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 2433,
        lsbFirst: true,
        min: 0,
        max: 37,
      },
      external: {
        type: 'cc',
        number: 11,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 37,
      default: 0,
      integer: true,
      list: [
        'Chromatic',
        '8-Tone Spanish',
        'Bhairav',
        'Dorian #4',
        'Dorian mode',
        'Half-Whole Dim',
        'Hirajoshi',
        'Insen',
        'Iwato',
        'Kumoi',
        'Locrian Mode',
        'Locrian Super',
        'Lydian Augment',
        'Lydian Dominan',
        'Lydian Mode',
        'Major Harmonic',
        'Major Pentatnc',
        'Major',
        'Messiaen 3',
        'Messiaen 4',
        'Messiaen 5',
        'Messiaen 6',
        'Messiaen 7',
        'Minor Blues',
        'Minor Harmonic',
        'Minor Hungrian',
        'Minor Mldc Dwn',
        'Minor Mldc Up',
        'Minor Pentatnc',
        'Minor',
        'Mixolydian Mde',
        'Pelog Selisir',
        'Pelog Tembung',
        'Phrygian Domnt',
        'Phrygian Mode',
        'Whole Tone',
        'Whole-Half Dim',
      ],
    },
    base: {
      name: 'Scales Base',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 2561,
        lsbFirst: true,
        min: 0,
        max: 11,
      },
      external: {
        type: 'cc',
        number: 12,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 11,
      default: 0,
      integer: true,
      list: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
    },
    shift: {
      name: 'Shift',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 2689,
        lsbFirst: true,
        min: 0,
        max: 32,
      },
      external: {
        type: 'cc',
        number: 19,
        min: 0,
        max: 32,
      },
      min: -16,
      max: 16,
      default: 0,
      unit: 'steps',
    },
    split: {
      name: 'Split',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 2817,
        lsbFirst: true,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 127,
      default: 127,
    },
    variant: {
      name: 'Variant',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 2818,
        lsbFirst: true,
        min: 0,
        max: 15,
      },
      min: 0,
      max: 15,
      default: 0,
      variant: 0, // global only
    },
    "torso-t1": {
      channel: {
        name: 'Torso T-1 Channel',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 14000,
          lsbFirst: true,
          min: 1,
          max: 16,
        },
        min: 1,
        max: 16,
        default: 16,
        variant: 0, // global only
      },
      scaleMode: {
        name: 'Torso T-1 Scale Mode',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 14001,
          lsbFirst: true,
          min: 0,
          max: 1,
        },
        min: 0,
        max: 1,
        default: 0,
        variant: 0, // global only
      },
    },
    reset_preset: {
      name: 'Reset Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 3073,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    grid: {
      name: 'Grid',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 16294,
        lsbFirst: true,
        min: 0,
        max: 2,
      },
      default: 2,
    },
    previous_preset: {
      name: 'Previous Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 8833,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    next_preset: {
      name: 'Next Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 8961,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    add_preset: {
      name: 'Add Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 9089,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    save_preset: {
      name: 'Save Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 13057,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    bank: {
      name: 'Bank',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 9217,
        lsbFirst: true,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 127,
      default: 0,
    },
    program: {
      name: 'Program',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 9345,
        lsbFirst: true,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 127,
      default: 0,
    },
    pattern: {
      name: 'Pattern',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 1410,
        lsbFirst: true,
        min: 0,
        max: 127,
      },
      min: 0,
      max: 127,
      default: 0,
    },
    mute: {
      name: 'Mute',
      type: 'parameter',
      surface: {
        type: 'nrpn',
        number: 12929,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
      default: 0,
    },
    deviations: {
      note: {
        maximum: {
          name: 'Note Maximum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2946,
            lsbFirst: true,
            min: 0,
            max: 254,
          },
          external: {
            type: 'cc',
            number: 90,
            min: 0,
            max: 127,
          },
          min: -127,
          max: 127,
          default: 0,
          unit: 'notes',
        },
        minimum: {
          name: 'Note Minimum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2949,
            lsbFirst: true,
            min: 0,
            max: 254,
          },
          external: {
            type: 'cc',
            number: 91,
            min: 0,
            max: 127,
          },
          min: -127,
          max: 127,
          default: 0,
          unit: 'notes',
        },
        density: {
          name: 'Note Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2947,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 92,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Note Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2950,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 93,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Note Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2948,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 94,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Note Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2951,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 95,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      velocity: {
        maximum: {
          name: 'Velocity Maximum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2952,
            lsbFirst: true,
            min: 0,
            max: 254,
          },
          external: {
            type: 'cc',
            number: 96,
            min: 0,
            max: 127,
          },
          min: -127,
          max: 127,
          default: 0,
        },
        minimum: {
          name: 'Velocity Minimum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2955,
            lsbFirst: true,
            min: 0,
            max: 254,
          },
          external: {
            type: 'cc',
            number: 97,
            min: 0,
            max: 127,
          },
          min: -127,
          max: 127,
          default: 0,
        },
        density: {
          name: 'Velocity Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2953,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 98,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Velocity Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2956,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 99,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Velocity Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2954,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 100,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Velocity Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2957,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 101,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      duration: {
        maximum: {
          name: 'Duration Maximum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2958,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 102,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        minimum: {
          name: 'Duration Minimum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2961,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 103,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        density: {
          name: 'Duration Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2959,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 104,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Duration Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2962,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 105,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Duration Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2960,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 106,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Duration Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2963,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 107,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      octave: {
        maximum: {
          name: 'Octave Maximum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2982,
            lsbFirst: true,
            min: 0,
            max: 10,
          },
          external: {
            type: 'cc',
            number: 108,
            min: 0,
            max: 127,
          },
          min: -5,
          max: 5,
          default: 0,
          unit: 'octave',
        },
        minimum: {
          name: 'Octave Minimum',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2983,
            lsbFirst: true,
            min: 0,
            max: 10,
          },
          external: {
            type: 'cc',
            number: 109,
            min: 0,
            max: 127,
          },
          min: -5,
          max: 5,
          default: 0,
          unit: 'octave',
        },
        density: {
          name: 'Octave Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2978,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 110,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Octave Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2980,
            lsbFirst: true,
            min: 0,
            max: 200,
          },
          external: {
            type: 'cc',
            number: 111,
            min: 0,
            max: 127,
          },
          min: -100,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Octave Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2979,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 112,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Octave Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2981,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 113,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      accent: {
        density: {
          name: 'Accent Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2970,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 114,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Accent Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2972,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 115,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Accent Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2971,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 116,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Accent Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2973,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 117,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      mute: {
        density: {
          name: 'Mute Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2974,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 118,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Mute Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2976,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 119,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Mute Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2975,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 120,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Mute Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2977,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 121,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
      device: {
        density: {
          name: 'Device Density',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2965,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 122,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        probability: {
          name: 'Device Probability',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2968,
            lsbFirst: true,
            min: 0,
            max: 100,
          },
          external: {
            type: 'cc',
            number: 123,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 100,
          default: 0,
          unit: '%',
        },
        euclidian: {
          name: 'Device Euclidian',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2966,
            lsbFirst: true,
            min: 0,
            max: 16,
          },
          external: {
            type: 'cc',
            number: 124,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 16,
          default: 0,
          unit: 'pulses',
          precision: 0,
        },
        rotation: {
          name: 'Device Rotation',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 2969,
            lsbFirst: true,
            min: 0,
            max: 30,
          },
          external: {
            type: 'cc',
            number: 125,
            min: 0,
            max: 127,
          },
          min: -15,
          max: 15,
          default: 0,
          unit: 'steps',
          precision: 0,
        },
      },
    },
    lfo: [{
      device: {
        A: {
          name: 'LFO 1 Device A',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5249,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 64,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        B: {
          name: 'LFO 1 Device B',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5377,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 65,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      control: {
        name: 'LFO 1 Control',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3201,
          lsbFirst: true,
          min: 0,
          max: 255,
        },
        min: 0,
        max: 255,
        default: 0,
      },
      shape: {
        name: 'LFO 1 Shape',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 7425,
          lsbFirst: true,
          min: 0,
          max: 5,
        },
        external: {
          type: 'cc',
          number: 66,
          min: 0,
          max: 5,
        },
        min: 0,
        max: 5,
        default: 0,
        list: ['sine', 'triangle', 'saw-up', 'saw-down', 'square', 'random'],
      },
      rate: {
        name: 'LFO 1 Rate',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3329,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        external: {
          type: 'cc',
          number: 67,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 64,
      },
      phase: {
        name: 'LFO 1 Phase',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3457,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 68,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      amount: {
        name: 'LFO 1 Amount',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3585,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 69,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      offset: {
        name: 'LFO 1 Offset',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3713,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 70,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 50,
        unit: '%',
      },
      density: {
        name: 'LFO 1 Density',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 7809,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 127,
      },
      show: {
        name: 'LFO 1 Show',
        type: 'feedback',
        surface: {
          type: 'nrpn',
          number: 7041,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 0,
        silent: true,
      },
    }, {
      device: {
        A: {
          name: 'LFO 2 Device A',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5505,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 71,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        B: {
          name: 'LFO 2 Device B',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5633,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 72,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      control: {
        name: 'LFO 2 Control',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3841,
          lsbFirst: true,
          min: 0,
          max: 255,
        },
        min: 0,
        max: 255,
        default: 0,
      },
      shape: {
        name: 'LFO 2 Shape',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 7553,
          lsbFirst: true,
          min: 0,
          max: 5,
        },
        external: {
          type: 'cc',
          number: 73,
          min: 0,
          max: 5,
        },
        min: 0,
        max: 5,
        default: 0,
        list: ['sine', 'triangle', 'saw-up', 'saw-down', 'square', 'random'],
      },
      rate: {
        name: 'LFO 2 Rate',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 3969,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        external: {
          type: 'cc',
          number: 74,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 64,
      },
      phase: {
        name: 'LFO 2 Phase',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4097,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 75,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      amount: {
        name: 'LFO 2 Amount',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4225,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 76,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      offset: {
        name: 'LFO 2 Offset',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4353,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 77,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 50,
        unit: '%',
      },
      density: {
        name: 'LFO 2 Density',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 7937,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        external: {
          type: 'cc',
          number: 78,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 127,
      },
      show: {
        name: 'LFO 2 Show',
        type: 'feedback',
        surface: {
          type: 'nrpn',
          number: 7169,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 0,
        silent: true,
      },
    }, {
      device: {
        A: {
          name: 'LFO 3 Device A',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5761,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 79,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        B: {
          name: 'LFO 3 Device B',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 5889,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          external: {
            type: 'cc',
            number: 80,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      control: {
        name: 'LFO 3 Control',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4481,
          lsbFirst: true,
          min: 0,
          max: 255,
        },
        min: 0,
        max: 255,
        default: 0,
      },
      shape: {
        name: 'LFO 3 Shape',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 7681,
          lsbFirst: true,
          min: 0,
          max: 5,
        },
        external: {
          type: 'cc',
          number: 81,
          min: 0,
          max: 5,
        },
        min: 0,
        max: 5,
        default: 0,
        list: ['sine', 'triangle', 'saw-up', 'saw-down', 'square', 'random'],
      },
      rate: {
        name: 'LFO 3 Rate',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4609,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        external: {
          type: 'cc',
          number: 82,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 64,
      },
      phase: {
        name: 'LFO 3 Phase',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4737,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 83,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      amount: {
        name: 'LFO 3 Amount',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4865,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 84,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      offset: {
        name: 'LFO 3 Offset',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 4993,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        external: {
          type: 'cc',
          number: 85,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 50,
        unit: '%',
      },
      density: {
        name: 'LFO 3 Density',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 8065,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        external: {
          type: 'cc',
          number: 86,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 127,
      },
      show: {
        name: 'LFO 3 Show',
        type: 'feedback',
        surface: {
          type: 'nrpn',
          number: 7297,
          lsbFirst: true,
          min: 0,
          max: 127,
        },
        min: 0,
        max: 127,
        default: 0,
        silent: true,
      },
    }, ],
    device: {
      A: {
        device: {
          name: 'Device A Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 8193,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        mute: {
          name: 'Device A Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 8449,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        port: {
          name: 'Device A Port',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6529,
            lsbFirst: true,
            min: 0,
            max: 63,
          },
          min: 0,
          max: 63,
          default: 0,
        },
        channel: {
          name: 'Device A Channel',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6657,
            lsbFirst: true,
            min: 1,
            max: 16,
          },
          min: 1,
          max: 16,
          default: 1,
        },
        bank: {
          name: 'Device A Bank',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6017,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        program: {
          name: 'Device A Program',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6145,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        previousBank: {
          name: 'Device A Previous Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6018,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        nextBank: {
          name: 'Device A Next Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6019,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        previous: {
          name: 'Device A Previous',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6148,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        next: {
          name: 'Device A Next',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6149,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        transpose: {
          name: 'Device A Transpose',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6146,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: -64,
          max: 63,
          default: 0,
          unit: 'notes',
        },
        dispatch: {
          name: 'Device A Dispatch',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16365,
            lsbFirst: true,
            min: 0,
            max: 45,
          },
          min: 0,
          max: 45,
          default: 0,
        },
      },
      B: {
        device: {
          name: 'Device B Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 8321,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        mute: {
          name: 'Device B Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 8577,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        port: {
          name: 'Device B Port',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6785,
            lsbFirst: true,
            min: 0,
            max: 63,
          },
          min: 0,
          max: 63,
          default: 0,
        },
        channel: {
          name: 'Device B Channel',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6913,
            lsbFirst: true,
            min: 1,
            max: 16,
          },
          min: 1,
          max: 16,
          default: 1,
        },
        bank: {
          name: 'Device B Bank',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6273,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        program: {
          name: 'Device B Program',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6401,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        previousBank: {
          name: 'Device B Previous Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6274,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        nextBank: {
          name: 'Device B Next Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6275,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        previous: {
          name: 'Device B Previous',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6402,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        next: {
          name: 'Device B Next',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 6403,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        transpose: {
          name: 'Device B Transpose',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 6147,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: -64,
          max: 63,
          default: 0,
          unit: 'notes',
        },
        dispatch: {
          name: 'Device B Dispatch',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16366,
            lsbFirst: true,
            min: 0,
            max: 45,
          },
          min: 0,
          max: 45,
          default: 0,
        },
      },
    },
    drums: {
      generate: {
        name: 'Drums Generate',
        type: 'action',
        surface: {
          type: 'nrpn',
          number: 16286,
          lsbFirst: true,
          min: 0,
          max: 1,
        },
        on: 1,
      },
      mute: {
        name: 'Drums Mute',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16290,
          lsbFirst: true,
          min: 0,
          max: 1,
        },
        on: 1,
        default: 0,
      },
      style: {
        name: 'Drums Style',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16288,
          lsbFirst: true,
          min: 0,
          max: 2,
        },
        default: 1,
      },
      steps: {
        name: 'Drums Steps',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16287,
          lsbFirst: true,
          min: 1,
          max: 128,
        },
        min: 1,
        max: 128,
        default: 16,
        unit: 'steps',
      },
      continue: {
        name: 'Drums Continue',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16289,
          lsbFirst: true,
          min: 0,
          max: 1,
        },
        on: 1,
        default: 0,
      },
      density: {
        name: 'Drums Density',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16293,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      probability: {
        name: 'Drums Probability',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16291,
          lsbFirst: true,
          min: 0,
          max: 100,
        },
        min: 0,
        max: 100,
        default: 100,
        unit: '%',
      },
      velocity: {
        name: 'Drums Velocity',
        type: 'parameter',
        surface: {
          type: 'nrpn',
          number: 16292,
          lsbFirst: true,
          min: 0,
          max: 200,
        },
        min: -100,
        max: 100,
        default: 0,
      },
      instrument: [{
        device: {
          name: 'Bass Drum Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16296,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Bass Drum Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16297,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 0,
        },
        mute: {
          name: 'Bass Drum Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16298,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Snare Drum Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16299,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Snare Drum Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16300,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 1,
        },
        mute: {
          name: 'Snare Drum Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16301,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Low Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16302,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Low Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16303,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 5,
        },
        mute: {
          name: 'Low Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16304,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Mid Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16305,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Mid Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16306,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 6,
        },
        mute: {
          name: 'Mid Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16307,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'High Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16308,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'High Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16309,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 7,
        },
        mute: {
          name: 'High Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16310,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Rim Shot Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16311,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Rim Shot Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16312,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 2,
        },
        mute: {
          name: 'Rim Shot Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16313,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Hand Clap Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16314,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Hand Clap Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16315,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 8,
        },
        mute: {
          name: 'Hand Clap Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16316,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Cow Bell Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16317,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Cow Bell Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16318,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 11,
        },
        mute: {
          name: 'Cow Bell Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16319,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Cymbal Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16320,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Cymbal Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16321,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 10,
        },
        mute: {
          name: 'Cymbal Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16322,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Open Hat Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16323,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Open Hat Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16324,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 9,
        },
        mute: {
          name: 'Open Hat Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16325,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        device: {
          name: 'Closed Hat Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16326,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('bacara', 10),
        },
        note: {
          name: 'Closed Hat Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16327,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 8,
        },
        mute: {
          name: 'Closed Hat Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16328,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, ],
      redrum: [{
        instrument: {
          name: 'Closed Hat Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16129,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 0,
        },
        generate: {
          name: 'Closed Hat Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16130,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Closed Hat Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16131,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Closed Hat Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16132,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 9),
        },
        note: {
          name: 'Closed Hat Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16133,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Closed Hat Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16134,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        instrument: {
          name: 'Open Hat Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16135,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 1,
        },
        generate: {
          name: 'Open Hat Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16136,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 1,
        },
        mute: {
          name: 'Open Hat Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16137,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Open Hat Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16138,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 10),
        },
        note: {
          name: 'Open Hat Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16139,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Open Hat Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16140,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        instrument: {
          name: 'Bass Tom Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16141,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 2,
        },
        generate: {
          name: 'Bass Tom Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16142,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Bass Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16143,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Bass Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16144,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 5),
        },
        note: {
          name: 'Bass Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16145,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Bass Tom Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16146,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        instrument: {
          name: 'Low Tom Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16147,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 6,
        },
        generate: {
          name: 'Low Tom Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16148,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Low Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16149,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Low Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16150,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 6),
        },
        note: {
          name: 'Low Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16151,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Low Tom Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16152,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      }, {
        instrument: {
          name: 'Bass Drum Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16153,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 10,
        },
        generate: {
          name: 'Bass Drum Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16154,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Bass Drum Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16155,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Bass Drum Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16156,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 1),
        },
        note: {
          name: 'Bass Drum Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16157,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Bass Drum Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16158,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      {
        instrument: {
          name: 'Snare Drum Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16159,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Snare Drum Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16160,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Snare Drum Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16161,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Snare Drum Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16162,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 2),
        },
        note: {
          name: 'Snare Drum Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16163,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Snare Drum Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16164,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      {
        instrument: {
          name: 'Cymbal Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16165,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Cymbal Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16166,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Cymbal Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16167,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Cymbal Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16168,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 11),
        },
        note: {
          name: 'Cymbal Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16169,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Cymbal Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16170,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      {
        instrument: {
          name: 'Cowbell Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16171,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Cowbell Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16172,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Cowbell Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16173,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Cowbell Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16174,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 12),
        },
        note: {
          name: 'Cowbell Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16175,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Cowbell Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16176,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },
      {
        instrument: {
          name: 'Mid Tom Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16177,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Mid Tom Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16178,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Mid Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16179,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Mid Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16180,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 7),
        },
        note: {
          name: 'Mid Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16181,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Mid Tom Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16182,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },

      {
        instrument: {
          name: 'High Tom Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16183,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'High Tom Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16184,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'High Tom Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16185,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'High Tom Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16186,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 8),
        },
        note: {
          name: 'High Tom Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16187,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'High Tom Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16188,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },

      {
        instrument: {
          name: 'Rim Shot Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16189,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Rim Shot Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16190,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Rim Shot Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16191,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Rim Shot Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16192,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 3),
        },
        note: {
          name: 'Rim Shot Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16193,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Rim Shot Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16194,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },


      {
        instrument: {
          name: 'Hand Clap Instrument',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16195,
            lsbFirst: true,
            min: 0,
            max: 11,
          },
          min: 0,
          max: 11,
          default: 9,
        },
        generate: {
          name: 'Hand Clap Generate',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16196,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        mute: {
          name: 'Hand Clap Mute',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16197,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        device: {
          name: 'Hand Clap Device',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16198,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: deviceToIndex('analog-rytm', 4),
        },
        note: {
          name: 'Hand Clap Note',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 16199,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          default: 36,
        },
        preview: {
          name: 'Hand Clap Preview',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 16200,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
      },



      ],
    },
    matrix: {
      slot: [{
        source: {
          name: 'Matrix Slot 1 Source',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 9473,
            lsbFirst: true,
            min: 0,
            max: matrixSources(),
          },
          min: 0,
          max: matrixSources(),
          default: 0,
        },
        reset: {
          name: 'Matrix Slot 1 Reset',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 9474,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        value: {
          name: 'Matrix Slot 1 Value',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12161,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
          silent: true,
        },
        slewLimiter: {
          name: 'Matrix Slot 1 Slew Limiter',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12545,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        destination: [{
          target: {
            name: 'Matrix Slot 1 Target 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 9601,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 1 Amount 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 9985,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 1 Target 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 9729,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 1 Amount 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10113,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 1 Target 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 9857,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 1 Amount 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10241,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, ],
      }, {
        source: {
          name: 'Matrix Slot 2 Source',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 10369,
            lsbFirst: true,
            min: 0,
            max: matrixSources(),
          },
          min: 0,
          max: matrixSources(),
          default: 0,
        },
        reset: {
          name: 'Matrix Slot 2 Reset',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 10370,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        value: {
          name: 'Matrix Slot 2 Value',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12289,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
          silent: true,
        },
        slewLimiter: {
          name: 'Matrix Slot 2 Slew Limiter',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12673,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        destination: [{
          target: {
            name: 'Matrix Slot 2 Target 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10497,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 2 Amount 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10881,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 2 Target 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10625,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 2 Amount 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11009,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 2 Target 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 10753,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 2 Amount 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11137,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, ],
      }, {
        source: {
          name: 'Matrix Slot 3 Source',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 11265,
            lsbFirst: true,
            min: 0,
            max: matrixSources(),
          },
          min: 0,
          max: matrixSources(),
          default: 0,
        },
        reset: {
          name: 'Matrix Slot 3 Reset',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 11266,
            lsbFirst: true,
            min: 0,
            max: 1,
          },
          on: 1,
          default: 0,
        },
        value: {
          name: 'Matrix Slot 3 Value',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12417,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
          silent: true,
        },
        slewLimiter: {
          name: 'Matrix Slot 3 Slew Limiter',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 12801,
            lsbFirst: true,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        destination: [{
          target: {
            name: 'Matrix Slot 3 Target 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11393,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 3 Amount 1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11777,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 3 Target 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11521,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 3 Amount 2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11905,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, {
          target: {
            name: 'Matrix Slot 3 Target 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 11649,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          amount: {
            name: 'Matrix Slot 3 Amount 3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 12033,
              lsbFirst: true,
              min: 0,
              max: 127,
            },
            min: -100,
            max: 100,
            default: 0,
            unit: '%',
          },
        }, ],
      }, ],
    },
  },
}
