const config = require('config')
const Midi = require('../lib/midi/midi')

function virusMacroControl(part, ctrl) {
  return {
    name: `Part #${part} Control #${ctrl}`,
    type: 'parameter',
    surface: {
      type: 'nrpn',
      number: 128 + ((part - 1) * 6) + (ctrl),
      lsbFirst: false,
      min: 0,
      max: 16383,
    },
    min: 0,
    max: 16383,
    default: 0,
  }
}

module.exports = {
  elements: {
    load: {
      name: 'Load',
      type: 'action',
      surface: {
        type: 'sysex',
        bytes: [0xF0, 0x7D, 0x00, 0x03, 0xF7],
        number: 0x03,
      },
    },
    previous_preset: {
      name: 'Previous Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 8833,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    next_preset: {
      name: 'Next Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 8961,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    add_preset: {
      name: 'Add Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 9089,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    save_preset: {
      name: 'Save Preset',
      type: 'action',
      surface: {
        type: 'nrpn',
        number: 13057,
        lsbFirst: true,
        min: 0,
        max: 1,
      },
      on: 1,
    },
    virus: {
      axyz: {
        part: {
          name: 'Virus Axyz Part',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 14848,
            lsbFirst: false,
            min: 0,
            max: 15,
          },
          min: 1,
          max: 16,
          default: 1,
        },
        recenter: {
          name: 'Virus Axyz Recenter',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14855,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        mode: {
          name: 'Virus Axyz Mode',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 14856,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          min: 0,
          max: 1,
          default: 0,
        },
        resetTargets: {
          name: 'Virus Axyz Reset Targets',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14857,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        select: {
          name: 'Virus Axyz Select',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14849,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        level: {
          name: 'Virus Axyz Level',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 14850,
            lsbFirst: false,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 100,
        },
        bank: {
          name: 'Virus Axyz Bank',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 14851,
            lsbFirst: false,
            min: 0,
            max: 16383,
          },
          min: 0,
          max: 16383,
          default: 0,
        },
        program: {
          name: 'Virus Axyz Program',
          type: 'parameter',
          surface: {
            type: 'nrpn',
            number: 14852,
            lsbFirst: false,
            min: 0,
            max: 127,
          },
          min: 0,
          max: 127,
          default: 0,
        },
        next: {
          name: 'Virus Axyz Next',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14853,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        previous: {
          name: 'Virus Axyz Previous',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14854,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        nextBank: {
          name: 'Virus Axyz Next Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14858,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        previousBank: {
          name: 'Virus Axyz Previous Bank',
          type: 'action',
          surface: {
            type: 'nrpn',
            number: 14859,
            lsbFirst: false,
            min: 0,
            max: 1,
          },
          on: 1,
        },
        x1: {
          control: {
            name: 'Virus Axyz X1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15361,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 20,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz X1 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15362,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 1,
          }, {
            name: 'Virus Axyz X1 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15363,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 2,
          }, ],
        },
        y1: {
          control: {
            name: 'Virus Axyz Y1',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15489,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 21,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz Y1 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15490,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 3,
          }, {
            name: 'Virus Axyz Y1 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15491,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          }, ],
        },
        x2: {
          control: {
            name: 'Virus Axyz X2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15617,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 23,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz X2 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15618,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 22,
          }, {
            name: 'Virus Axyz X2 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15619,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 27,
          }, ],
        },
        y2: {
          control: {
            name: 'Virus Axyz Y2',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15745,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 24,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz Y2 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15746,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 23,
          }, {
            name: 'Virus Axyz Y2 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15747,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 28,
          }, ],
        },
        x3: {
          control: {
            name: 'Virus Axyz X3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15873,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 26,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz X3 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15874,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 42,
          }, {
            name: 'Virus Axyz X3 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 15875,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 20,
          }, ],
        },
        y3: {
          control: {
            name: 'Virus Axyz Y3',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16001,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 27,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz Y3 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16002,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 45,
          }, {
            name: 'Virus Axyz Y3 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16003,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          }, ],
        },
        x4: {
          control: {
            name: 'Virus Axyz X4',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16004,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 29,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz X4 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16005,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 118,
          }, {
            name: 'Virus Axyz X4 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16006,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          }, ],
        },
        y4: {
          control: {
            name: 'Virus Axyz Y4',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16257,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            external: {
              type: 'cc',
              hiRes: true,
              number: 30,
              min: 0,
              max: 16383,
            },
            min: -1.0,
            max: 1.0,
            precision: 4,
            default: 0,
          },
          target: [{
            name: 'Virus Axyz Y4 Target A',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16258,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 119,
          }, {
            name: 'Virus Axyz Y4 Target B',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16259,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          }, ],
        },
      },
      mixer: {
        part: [{
          bank: {
            name: 'Virus Mixer Part 1 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14081,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 1 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14209,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 1 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14337,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 1 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14465,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 1 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14593,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 1 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14721,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, {
          bank: {
            name: 'Virus Mixer Part 2 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14082,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 2 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14210,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 2 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14338,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 2 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14466,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 2 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14594,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 2 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14722,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, {
          bank: {
            name: 'Virus Mixer Part 3 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14083,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 3 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14211,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 3 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14339,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 3 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14467,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 3 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14595,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 3 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14723,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, {
          bank: {
            name: 'Virus Mixer Part 4 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14084,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 4 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14212,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 4 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14340,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 4 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14468,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 4 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14596,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 4 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14724,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, {
          bank: {
            name: 'Virus Mixer Part 5 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14085,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 5 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14213,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 5 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14341,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 5 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14469,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 5 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14597,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 5 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14725,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, {
          bank: {
            name: 'Virus Mixer Part 6 Bank',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14086,
              lsbFirst: false,
              min: 0,
              max: 16383,
            },
            min: 0,
            max: 16383,
            default: 0,
          },
          program: {
            name: 'Virus Mixer Part 6 Program',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14214,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
          next: {
            name: 'Virus Mixer Part 6 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14342,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Mixer Part 6 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14470,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          select: {
            name: 'Virus Mixer Part 6 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 14598,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          level: {
            name: 'Virus Mixer Part 6 Level',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 14726,
              lsbFirst: false,
              min: 0,
              max: 127,
            },
            min: 0,
            max: 127,
            default: 0,
          },
        }, ],
      },
      macros: {
        part: [{
          control: [virusMacroControl(1, 1), virusMacroControl(1, 2), virusMacroControl(1, 3), virusMacroControl(1, 4), virusMacroControl(1, 5), virusMacroControl(1, 6)]
        }, {
          control: [virusMacroControl(2, 1), virusMacroControl(2, 2), virusMacroControl(2, 3), virusMacroControl(2, 4), virusMacroControl(2, 5), virusMacroControl(2, 6)]
        }, {
          control: [virusMacroControl(3, 1), virusMacroControl(3, 2), virusMacroControl(3, 3), virusMacroControl(3, 4), virusMacroControl(3, 5), virusMacroControl(3, 6)]
        }, {
          control: [virusMacroControl(4, 1), virusMacroControl(4, 2), virusMacroControl(4, 3), virusMacroControl(4, 4), virusMacroControl(4, 5), virusMacroControl(4, 6)]
        }, {
          control: [virusMacroControl(5, 1), virusMacroControl(5, 2), virusMacroControl(5, 3), virusMacroControl(5, 4), virusMacroControl(5, 5), virusMacroControl(5, 6)]
        }, {
          control: [virusMacroControl(6, 1), virusMacroControl(6, 2), virusMacroControl(6, 3), virusMacroControl(6, 4), virusMacroControl(6, 5), virusMacroControl(6, 6)]
        }, ],
      },
      search: {
        part: [{
          select: {
            name: 'Virus Search Part 1 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16261,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 1 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16262,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 1 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16263,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 1 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16264,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, {
          select: {
            name: 'Virus Search Part 2 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16265,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 2 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16266,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 2 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16267,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 2 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16268,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, {
          select: {
            name: 'Virus Search Part 3 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16269,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 3 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16270,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 3 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16271,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 3 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16272,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, {
          select: {
            name: 'Virus Search Part 4 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16273,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 4 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16274,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 4 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16275,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 4 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16276,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, {
          select: {
            name: 'Virus Search Part 5 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16277,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 5 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16278,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 5 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16279,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 5 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16280,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, {
          select: {
            name: 'Virus Search Part 6 Select',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16281,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          category: {
            name: 'Virus Search Part 6 Category',
            type: 'parameter',
            surface: {
              type: 'nrpn',
              number: 16282,
              lsbFirst: false,
              min: 0,
              max: 22,
            },
            min: 0,
            max: 22,
            default: 0,
          },
          next: {
            name: 'Virus Search Part 6 Next',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16283,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
          previous: {
            name: 'Virus Search Part 6 Previous',
            type: 'action',
            surface: {
              type: 'nrpn',
              number: 16284,
              lsbFirst: false,
              min: 0,
              max: 1,
            },
            on: 1,
          },
        }, ],
      },
    },
  },
}
